apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-assignment-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-classifier
  template:
    metadata:
      labels:
        app: iris-classifier
    spec:
      serviceAccountName: telemetry-access
      containers:
      - name: iris-api
        image: DOCKER_IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /ready_check
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /live_check
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi