apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iris-classifier-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mlops-assignment-app # This MUST match the name in your deployment.yaml
  minReplicas: 2
  maxReplicas: 5 # The maximum number of pods to scale up to
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # The target CPU utilization percentage. When the average CPU across
        # all pods goes above 60%, the HPA will start creating new pods.
        averageUtilization: 60