apiVersion: v1
kind: Service
metadata:
  name: iris-classifier-service
spec:
  type: LoadBalancer # Exposes the service externally using a cloud provider's load balancer
  selector:
    app: iris-classifier
  ports:
  - protocol: TCP
    port: 80       # The port the service is exposed on
    targetPort: 8000 # The port the container is listening on